# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mod_pb2 as mod__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mod_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMod = channel.unary_unary(
                '/mod.ModService/CreateMod',
                request_serializer=mod__pb2.CreateModRequest.SerializeToString,
                response_deserializer=mod__pb2.CreateModResponse.FromString,
                _registered_method=True)
        self.SetStatus = channel.unary_unary(
                '/mod.ModService/SetStatus',
                request_serializer=mod__pb2.SetStatusRequest.SerializeToString,
                response_deserializer=mod__pb2.SetStatusResponse.FromString,
                _registered_method=True)
        self.GetModDownloadLink = channel.unary_unary(
                '/mod.ModService/GetModDownloadLink',
                request_serializer=mod__pb2.GetModDownloadLinkRequest.SerializeToString,
                response_deserializer=mod__pb2.GetModDownloadLinkResponse.FromString,
                _registered_method=True)
        self.GetMods = channel.unary_unary(
                '/mod.ModService/GetMods',
                request_serializer=mod__pb2.GetModsRequest.SerializeToString,
                response_deserializer=mod__pb2.GetModsResponse.FromString,
                _registered_method=True)


class ModServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModDownloadLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMod': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMod,
                    request_deserializer=mod__pb2.CreateModRequest.FromString,
                    response_serializer=mod__pb2.CreateModResponse.SerializeToString,
            ),
            'SetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStatus,
                    request_deserializer=mod__pb2.SetStatusRequest.FromString,
                    response_serializer=mod__pb2.SetStatusResponse.SerializeToString,
            ),
            'GetModDownloadLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModDownloadLink,
                    request_deserializer=mod__pb2.GetModDownloadLinkRequest.FromString,
                    response_serializer=mod__pb2.GetModDownloadLinkResponse.SerializeToString,
            ),
            'GetMods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMods,
                    request_deserializer=mod__pb2.GetModsRequest.FromString,
                    response_serializer=mod__pb2.GetModsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mod.ModService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mod.ModService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mod.ModService/CreateMod',
            mod__pb2.CreateModRequest.SerializeToString,
            mod__pb2.CreateModResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mod.ModService/SetStatus',
            mod__pb2.SetStatusRequest.SerializeToString,
            mod__pb2.SetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModDownloadLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mod.ModService/GetModDownloadLink',
            mod__pb2.GetModDownloadLinkRequest.SerializeToString,
            mod__pb2.GetModDownloadLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mod.ModService/GetMods',
            mod__pb2.GetModsRequest.SerializeToString,
            mod__pb2.GetModsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
