name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.4"
      
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10.4"
          cache: true
          cache-dependency-path: pdm.lock

      - name: Cache PDM packages
        id: cache-pdm
        uses: actions/cache@v3
        with:
          path: __pypackages__
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}

      - name: Install dependencies
        if: steps.cache-pdm.outputs.cache-hit != 'true'
        run: pdm install

      - name: Run lint
        run: pdm run make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.4"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10.4"
          cache: true
          cache-dependency-path: pdm.lock

      - name: Cache PDM packages
        id: cache-pdm-test
        uses: actions/cache@v3
        with:
          path: __pypackages__
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}

      - name: Install dependencies
        if: steps.cache-pdm-test.outputs.cache-hit != 'true'
        run: pdm install

      - name: Run test
        run: pdm run make test
