name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with: { python-version: "3.10.4" }

      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip pdm
          pdm install --dev

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}

  lint:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}

      - name: Add venv to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - run: pdm run make lint

  test:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}

      - name: Add venv to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - run: pdm run make test
